# Enums Python fixos e compartilhados entre entidades (ex: Candidato e Vaga).
# Só ficam aqui classificações fechadas que não precisam ser editáveis em
# runtime nem crescem com frequência — o contrário disso é modelado como
# tabela de cadastro (`app/models/cadastros.py`), não Enum (ver critério em
# docs/APRENDIZADO-BACKEND.md).
import enum


class AreaEstudo(str, enum.Enum):
    """Área de conhecimento de uma formação acadêmica (baseada nas áreas do
    MEC/CNE)."""

    EDUCACAO = "EDUCACAO"
    ARTES_E_HUMANIDADES = "ARTES_E_HUMANIDADES"
    CIENCIAS_SOCIAIS_E_COMPORTAMENTAIS = "CIENCIAS_SOCIAIS_E_COMPORTAMENTAIS"
    COMUNICACAO_E_INFORMACAO = "COMUNICACAO_E_INFORMACAO"
    NEGOCIOS_E_ADMINISTRACAO = "NEGOCIOS_E_ADMINISTRACAO"
    DIREITO = "DIREITO"
    CIENCIAS_NATURAIS = "CIENCIAS_NATURAIS"
    MATEMATICA_E_ESTATISTICA = "MATEMATICA_E_ESTATISTICA"
    COMPUTACAO_E_TECNOLOGIA_DA_INFORMACAO = "COMPUTACAO_E_TECNOLOGIA_DA_INFORMACAO"
    ENGENHARIAS = "ENGENHARIAS"
    ARQUITETURA_E_CONSTRUCAO = "ARQUITETURA_E_CONSTRUCAO"
    PRODUCAO_INDUSTRIAL = "PRODUCAO_INDUSTRIAL"
    AGRICULTURA_E_VETERINARIA = "AGRICULTURA_E_VETERINARIA"
    SAUDE_E_BEM_ESTAR = "SAUDE_E_BEM_ESTAR"
    TURISMO_HOTELARIA_E_GASTRONOMIA = "TURISMO_HOTELARIA_E_GASTRONOMIA"
    SEGURANCA_E_DEFESA = "SEGURANCA_E_DEFESA"
    TRANSPORTES = "TRANSPORTES"
    INTERDISCIPLINAR = "INTERDISCIPLINAR"
    OTHER = "OTHER"


class TipoTrabalho(str, enum.Enum):
    """Tipo de vínculo de uma experiência profissional (`Experiencia`)."""

    TEMPO_INTEGRAL = "TEMPO_INTEGRAL"
    MEIO_PERIODO = "MEIO_PERIODO"
    AUTONOMO = "AUTONOMO"
    FREELANCER = "FREELANCER"
    CONTRATO = "CONTRATO"
    ESTAGIO = "ESTAGIO"
    APRENDIZ = "APRENDIZ"
    CONTRATO_INDIRETO = "CONTRATO_INDIRETO"
    PROGRAMA_DE_LIDERANCA = "PROGRAMA_DE_LIDERANCA"
    OTHER = "OTHER"


class LocalTrabalho(str, enum.Enum):
    """Modelo de local de trabalho — usado tanto por uma experiência
    profissional (`Experiencia.local_trabalho`) quanto por uma vaga
    (`Vaga.local_trabalho`); mesmo tipo Postgres (`local_trabalho`) nos dois
    lugares."""

    PRESENCIAL = "PRESENCIAL"
    HIBRIDO = "HIBRIDO"
    REMOTO = "REMOTO"


class AreaProfissional(str, enum.Enum):
    """Área profissional de uma vaga (`Vaga.area_profissional`) — o que o
    cargo faz, não o setor/indústria da empresa que o publica (uma empresa
    farmacêutica pode ter uma vaga de TI, de advogado, de operador de
    máquina etc.). Classificação fechada, por isso Enum e não cadastro."""

    ADMINISTRACAO = "ADMINISTRACAO"
    RECURSOS_HUMANOS = "RECURSOS_HUMANOS"
    JURIDICO_ADVOCACIA = "JURIDICO_ADVOCACIA"
    CONTABILIDADE = "CONTABILIDADE"
    FINANCEIRO = "FINANCEIRO"
    MARKETING = "MARKETING"
    VENDAS_COMERCIAL = "VENDAS_COMERCIAL"
    ATENDIMENTO_AO_CLIENTE = "ATENDIMENTO_AO_CLIENTE"
    TECNOLOGIA_DA_INFORMACAO = "TECNOLOGIA_DA_INFORMACAO"
    ENGENHARIA_CIVIL = "ENGENHARIA_CIVIL"
    ENGENHARIA_MECANICA = "ENGENHARIA_MECANICA"
    ENGENHARIA_ELETRICA = "ENGENHARIA_ELETRICA"
    ENGENHARIA_DE_PRODUCAO = "ENGENHARIA_DE_PRODUCAO"
    ENGENHARIA_QUIMICA = "ENGENHARIA_QUIMICA"
    ENGENHARIA_DE_ALIMENTOS = "ENGENHARIA_DE_ALIMENTOS"
    ENGENHARIA_AMBIENTAL = "ENGENHARIA_AMBIENTAL"
    ARQUITETURA = "ARQUITETURA"
    LOGISTICA = "LOGISTICA"
    COMPRAS_SUPRIMENTOS = "COMPRAS_SUPRIMENTOS"
    PRODUCAO_OPERACOES_INDUSTRIAIS = "PRODUCAO_OPERACOES_INDUSTRIAIS"
    MANUTENCAO_INDUSTRIAL = "MANUTENCAO_INDUSTRIAL"
    QUALIDADE = "QUALIDADE"
    SEGURANCA_DO_TRABALHO = "SEGURANCA_DO_TRABALHO"
    SAUDE_E_MEDICINA = "SAUDE_E_MEDICINA"
    ENFERMAGEM = "ENFERMAGEM"
    FARMACIA = "FARMACIA"
    NUTRICAO = "NUTRICAO"
    PSICOLOGIA = "PSICOLOGIA"
    EDUCACAO_DOCENCIA = "EDUCACAO_DOCENCIA"
    DESIGN_GRAFICO = "DESIGN_GRAFICO"
    COMUNICACAO_JORNALISMO = "COMUNICACAO_JORNALISMO"
    PUBLICIDADE_E_PROPAGANDA = "PUBLICIDADE_E_PROPAGANDA"
    RECEPCAO_SECRETARIADO = "RECEPCAO_SECRETARIADO"
    ALMOXARIFADO = "ALMOXARIFADO"
    TRANSPORTE_MOTORISTA = "TRANSPORTE_MOTORISTA"
    CONSTRUCAO_CIVIL = "CONSTRUCAO_CIVIL"
    ELETRICISTA = "ELETRICISTA"
    MECANICA_AUTOMOTIVA = "MECANICA_AUTOMOTIVA"
    METALURGIA_SOLDA = "METALURGIA_SOLDA"
    AGRONOMIA = "AGRONOMIA"
    VETERINARIA = "VETERINARIA"
    ZOOTECNIA = "ZOOTECNIA"
    MEIO_AMBIENTE_SUSTENTABILIDADE = "MEIO_AMBIENTE_SUSTENTABILIDADE"
    AUDITORIA = "AUDITORIA"
    CONTROLADORIA = "CONTROLADORIA"
    ECONOMIA = "ECONOMIA"
    ESTATISTICA_CIENCIA_DE_DADOS = "ESTATISTICA_CIENCIA_DE_DADOS"
    BIOMEDICINA = "BIOMEDICINA"
    BIOLOGIA_BIOTECNOLOGIA = "BIOLOGIA_BIOTECNOLOGIA"
    QUIMICA_LABORATORIO = "QUIMICA_LABORATORIO"
    TURISMO_HOTELARIA = "TURISMO_HOTELARIA"
    GASTRONOMIA = "GASTRONOMIA"
    SERVICOS_GERAIS_LIMPEZA = "SERVICOS_GERAIS_LIMPEZA"
    SEGURANCA_PATRIMONIAL = "SEGURANCA_PATRIMONIAL"
    TELECOMUNICACOES = "TELECOMUNICACOES"
    ELETRONICA = "ELETRONICA"
    AUTOMACAO_INDUSTRIAL = "AUTOMACAO_INDUSTRIAL"
    COMERCIO_EXTERIOR = "COMERCIO_EXTERIOR"
    RELACOES_PUBLICAS = "RELACOES_PUBLICAS"
    GESTAO_DE_PROJETOS = "GESTAO_DE_PROJETOS"
    OUTRA = "OUTRA"
