"""create initial schema

Revision ID: 717e70bd40da
Revises: 
Create Date: 2026-09-04 14:53:03.568381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717e70bd40da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cd_categorias_skill',
    sa.Column('categoria_skill_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('categoria_skill_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_logs_auditoria',
    sa.Column('log_auditoria_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('alvo_id', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_auditoria_id')
    )
    op.create_table('cd_niveis',
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('nivel_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_status_candidatura',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_status_denuncia',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('status_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_status_validacao_empresa',
    sa.Column('status_validacao_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('status_validacao_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_tipos_contrato',
    sa.Column('tipo_contrato_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_contrato_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_tipos_denuncia',
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_tipos_usuario',
    sa.Column('tipo_usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_usuario_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_candidatos',
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('setor_atuacao', sa.String(), nullable=False),
    sa.Column('localidade', sa.String(), nullable=False),
    sa.Column('anos_experiencia', sa.Integer(), nullable=False),
    sa.Column('perfil_completo', sa.Integer(), nullable=False),
    sa.Column('curriculo_url', sa.String(), nullable=True),
    sa.Column('alertas_ativos', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['nivel_id'], ['cd_niveis.nivel_id'], ),
    sa.PrimaryKeyConstraint('candidato_id')
    )
    op.create_table('cd_denuncias',
    sa.Column('denuncia_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('alvo', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['cd_status_denuncia.status_id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['cd_tipos_denuncia.tipo_id'], ),
    sa.PrimaryKeyConstraint('denuncia_id')
    )
    op.create_table('cd_empresas',
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('setor', sa.String(), nullable=False),
    sa.Column('status_validacao_id', sa.Integer(), nullable=False),
    sa.Column('sede', sa.String(), nullable=False),
    sa.Column('logo_inicial', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['status_validacao_id'], ['cd_status_validacao_empresa.status_validacao_id'], ),
    sa.PrimaryKeyConstraint('empresa_id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('cd_certificacoes',
    sa.Column('certificacao_id', sa.Integer(), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('validada', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['cd_candidatos.candidato_id'], ),
    sa.PrimaryKeyConstraint('certificacao_id')
    )
    op.create_table('cd_skills',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria_skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['cd_candidatos.candidato_id'], ),
    sa.ForeignKeyConstraint(['categoria_skill_id'], ['cd_categorias_skill.categoria_skill_id'], ),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('candidato_id', 'nome', name='uq_skill_candidato_nome')
    )
    op.create_table('cd_usuarios',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('tipo_usuario_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('candidato_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['cd_candidatos.candidato_id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['cd_empresas.empresa_id'], ),
    sa.ForeignKeyConstraint(['tipo_usuario_id'], ['cd_tipos_usuario.tipo_usuario_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('candidato_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cd_vagas',
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('setor_atuacao', sa.String(), nullable=False),
    sa.Column('distrito', sa.String(), nullable=False),
    sa.Column('nivel_id', sa.Integer(), nullable=False),
    sa.Column('salario_min', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salario_max', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tipo_contrato_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('data_publicacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['cd_empresas.empresa_id'], ),
    sa.ForeignKeyConstraint(['nivel_id'], ['cd_niveis.nivel_id'], ),
    sa.ForeignKeyConstraint(['tipo_contrato_id'], ['cd_tipos_contrato.tipo_contrato_id'], ),
    sa.PrimaryKeyConstraint('vaga_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('cd_candidaturas',
    sa.Column('candidatura_id', sa.Integer(), nullable=False),
    sa.Column('candidato_id', sa.Integer(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('data_aplicacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('parecer_rh', sa.Text(), nullable=True),
    sa.Column('parecer_tecnico', sa.Text(), nullable=True),
    sa.Column('data_entrevista', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['cd_candidatos.candidato_id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['cd_status_candidatura.status_id'], ),
    sa.ForeignKeyConstraint(['vaga_id'], ['cd_vagas.vaga_id'], ),
    sa.PrimaryKeyConstraint('candidatura_id'),
    sa.UniqueConstraint('candidato_id', 'vaga_id', name='uq_candidatura_candidato_vaga')
    )
    op.create_table('cd_vaga_habilidades',
    sa.Column('vaga_habilidade_id', sa.Integer(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vaga_id'], ['cd_vagas.vaga_id'], ),
    sa.PrimaryKeyConstraint('vaga_habilidade_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cd_vaga_habilidades')
    op.drop_table('cd_candidaturas')
    op.drop_table('cd_vagas')
    op.drop_table('cd_usuarios')
    op.drop_table('cd_skills')
    op.drop_table('cd_certificacoes')
    op.drop_table('cd_empresas')
    op.drop_table('cd_denuncias')
    op.drop_table('cd_candidatos')
    op.drop_table('cd_tipos_usuario')
    op.drop_table('cd_tipos_denuncia')
    op.drop_table('cd_tipos_contrato')
    op.drop_table('cd_status_validacao_empresa')
    op.drop_table('cd_status_denuncia')
    op.drop_table('cd_status_candidatura')
    op.drop_table('cd_niveis')
    op.drop_table('cd_logs_auditoria')
    op.drop_table('cd_categorias_skill')
    # ### end Alembic commands ###
